version: '3'

networks:
  ncms:
    driver: bridge

volumes:
  dbdata:

services:
  broker:
    image: eclipse-mosquitto
#    command: "/bin/sh /mosquitto/mqrun.sh"
#    command: "mosquitto_passwd -U /mosquitto/etc/passwd"
#    command: >
#      sh -c "mosquitto_passwd -c /mosquitto/etc/passwd tarek21
#      && mosquitto_passwd -b /mosquitto/etc/passwd tarek21 tarek21"
    ports:
      - 1884:1883
      - 9001:9001
    networks:
      - ncms
    volumes:
      - "./mosquitto:/mosquitto"
      - "./mosquitto/log:/mosquitto/log"
      - "./mosquitto/data/:/mosquitto/data/"
      - "./mosquitto/etc/passwd:/mosquitto/etc/passwd"

  app:
    image: node:12.18
    restart: always
    working_dir: "/app"
    command: "npm run start:dev"
    ports:
      - 3000:8080
    networks:
      - ncms
    links:
      - broker
      - mongo
    environment:
      NODE_ENV: development
      NODE_TLS_REJECT_UNAUTHORIZED: 0
      NO_SSL_MODE: 1
      APP_NAME: NCSM
      EXPRESS_PORT: 8080
      DB_URL: mongodb://root:root@mongo:27017/ncms?authSource=admin
      SECRET: mytestapp!!
      MIGRATE_dbConnectionUri: mongodb://root:root@mongo:27017/ncms?authSource=admin
      MQTT_HOST: ncms_broker_1
      IO_HOST: localhost:3000
    volumes:
      - "./:/app"
      - "./logs:/root/.npm/_logs"

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    networks:
      - ncms
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - "dbdata:/data/db"
#      - "./config_db:/data/configdb"